
package proyectofinal.biblioteca.Vistas;
import bibliotecatpfinal.Vistas.FormularioEjemplares;

import java.awt.Color;

/**
 *
 * @author Familia
 */
public class Menuview extends javax.swing.JFrame {

    public Menuview() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setSize(900, 720);// modifica el tamaño de la ventana*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jGestionLB = new javax.swing.JMenuItem();
        jmEjemplares = new javax.swing.JMenu();
        jmFormu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmPrestamos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemLectores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jMenu1.setText("Libros");

        jGestionLB.setText("Gestion de libros");
        jGestionLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionLBActionPerformed(evt);
            }
        });
        jMenu1.add(jGestionLB);

        jMenuBar1.add(jMenu1);

        jmEjemplares.setText("Ejemplares");
        jmEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEjemplaresActionPerformed(evt);
            }
        });

        jmFormu.setText("Formulario de Ejemplares");
        jmFormu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormuActionPerformed(evt);
            }
        });
        jmEjemplares.add(jmFormu);

        jMenuBar1.add(jmEjemplares);

        jMenu3.setText("Prestamos");

        jmPrestamos.setText("Gestion de Prestamos");
        jmPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrestamosActionPerformed(evt);
            }
        });
        jMenu3.add(jmPrestamos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Lectores");

        itemLectores.setText("Gestion de Lectores");
        itemLectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLectoresActionPerformed(evt);
            }
        });
        jMenu4.add(itemLectores);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGestionLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionLBActionPerformed
        GestionDeLibros verventana = new GestionDeLibros();
        jEscritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_jGestionLBActionPerformed

    private void itemLectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLectoresActionPerformed
        // GESTION DE LECTORES
        jEscritorio.removeAll();
        jEscritorio.repaint();
        GestionDeLectores lectores = new GestionDeLectores();
        lectores.setVisible(true);
        /*  lectores.getContentPane().setBackground(new Color(68, 167, 132));*/
        jEscritorio.add(lectores);
        // verventana.show();

    }//GEN-LAST:event_itemLectoresActionPerformed

    private void jmEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEjemplaresActionPerformed
            // Instancia el formulario de ejemplares
   
    }//GEN-LAST:event_jmEjemplaresActionPerformed

    private void jmFormuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormuActionPerformed
         this.jEscritorio.add(new FormularioEjemplares());
        
        FormularioEjemplares ejemplar = new FormularioEjemplares();
        ejemplar.setVisible(true);
        jEscritorio.add(ejemplar);
         
                                        // TODO add your handling code here:
    }//GEN-LAST:event_jmFormuActionPerformed

    private void jmPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrestamosActionPerformed
        GestionDePrestamos prestamosFrame = new GestionDePrestamos();
        jEscritorio.add(prestamosFrame);
        prestamosFrame.setVisible(true); 
    }//GEN-LAST:event_jmPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLectores;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuItem jGestionLB;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmEjemplares;
    private javax.swing.JMenuItem jmFormu;
    private javax.swing.JMenuItem jmPrestamos;
    // End of variables declaration//GEN-END:variables
}
